# Generated by Django 2.2.16 on 2021-10-13 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
