# Generated by Django 3.2.8 on 2021-10-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='review',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='genre_title',
            name='genre',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='genre_title',
            name='title',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.IntegerField(),
        ),
    ]
