# Generated by Django 3.2.8 on 2021-10-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='titles',
            name='rating',
        ),
    ]
