# Generated by Django 3.2.8 on 2021-10-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0002_remove_titles_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Произведение'),
        ),
    ]
