# Generated by Django 2.2.16 on 2021-10-13 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0002_auto_20211013_1029'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
