# Generated by Django 2.2.16 on 2021-10-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0002_auto_20211015_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=256, unique=True, verbose_name='Жанр'),
        ),
    ]
