# Generated by Django 2.2.16 on 2021-10-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0002_auto_20211014_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(verbose_name='Год публикации'),
        ),
    ]
