# Generated by Django 2.2.16 on 2021-10-13 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0004_auto_20211013_1036'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Titles',
            new_name='Title',
        ),
    ]
