# Generated by Django 2.2.16 on 2021-10-13 15:50

from django.db import migrations, models
import django.db.models.functions.datetime


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0005_auto_20211013_1823'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(check=models.Q(year__gt=django.db.models.functions.datetime.Now()), name='year_cannot_be_bigger_then_current'),
        ),
    ]
