# Generated by Django 2.2.16 on 2021-10-16 11:51

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api_yamdb', '0005_auto_20211016_1651'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='review',
            name='name_not_title',
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, author=django.db.models.expressions.F('title')), name='name_not_title'),
        ),
    ]
