# Generated by Django 2.2.16 on 2021-10-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20211016_2053'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='title',
            constraint=models.CheckConstraint(check=models.Q(year__lte=2021), name='year_cannot_be_bigger_then_current'),
        ),
    ]
