# Generated by Django 2.2.16 on 2021-10-15 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCSRF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Пользователь')),
                ('token', models.TextField(blank=True, help_text='Ключ для регистрации telegram пользователя (клиента) на сайте.', max_length=32, verbose_name='CSRF ключ')),
                ('date', models.BigIntegerField(default=0, verbose_name='срок годности CSRF')),
            ],
            options={
                'verbose_name': 'CSRF token',
            },
        ),
    ]
