# Generated by Django 2.2.16 on 2021-10-15 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('code', models.CharField(max_length=30, verbose_name='confirmation_code')),
            ],
        ),
    ]
