# Generated by Django 2.2.16 on 2021-10-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'u'), ('moderator', 'm'), ('admin', 'a')], max_length=9, verbose_name='Права'),
        ),
    ]
